---
- name: "basic debian based server setup"
  include_role:
    name: oozou.basic-server-setup
  vars:
    default_additional_packages_to_install:
      - nodejs
      - imagemagick
      - libpq-dev
    additional_packages_to_install:
      "{{ default_additional_packages_to_install + basic_server_setup.additional_packages_to_install }}"
