# 0. ensure variables are present
# 1. install python on ubuntu 16.04
# 2. install basic packages
# 3. setup firewall
- include: basic_server_setup.yml
  tags:
    - basic_server_setup

# 4. set ubuntu user
- include: ubuntu.yml
  tags:
    - ubuntu

# 4. create deployer user account
- include: deployer.yml
  tags:
    - deployer

# 8. install rbenv, ruby and bundler gem
- include: rbenv.yml
  tags:
    - rbenv

# 5. install ntp
- include: ntp.yml
  tags:
    - ntp

# 6. install and configure nginx
- include: nginx.yml
  tags:
    - nginx

# 7. install systemd files for puma and sidekiq
- include: systemd_services.yml
  tags:
    - systemd_services

# 9. install postgresql
- include: postgresql.yml
  when: database.host == 'localhost'
  tags:
    - postgresql

# 10. make shared directory for capistrano
# 11. deploy rails config files into shared directory
- include: deploy_rails_config.yml
  tags:
    - deploy_rails_config
