# 0. ensure variables are present
# 1. install python on ubuntu 16.04
# 2. install basic packages
- include: basic_server_setup.yml
  tags:
    - basic_server_setup

# 3. create deployer user account
- include: deployer_user.yml
  tags:
    - deployer_user

# 4. install rbenv, ruby and bundler gem
- include: rbenv.yml
  tags:
    - rbenv

# 5. install ntp
- include: ntp.yml
  tags:
    - ntp

# 6. install and configure nginx
- include: nginx.yml
  tags:
    - nginx

# 7. install systemd files for puma and sidekiq
- include: systemd_services.yml
  tags:
    - systemd_services

# 8. install postgresql
- include: postgresql.yml
  when: database.host == 'localhost'
  tags:
    - postgresql

# 9. make shared directory for capistrano
# 10. deploy rails config files into shared directory
- include: deploy_rails_config.yml
  tags:
    - deploy_rails_config
